[package]
name = "super_awesome_composer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = "0.8"
druid-shell = "0.8"
lyon = "1.0"
num-rational = "0.4"
